#!/usr/bin/env python3.10
"""
INT8 Quantize face_landmark.tflite via JSON FlatBuffer manipulation.

Strategy:
  1. Parse model JSON (generated by flatc)
  2. Graph surgery: FLOAT16 tensors + DEQUANTIZE ops → FLOAT32 constant tensors
  3. Run calibration with TFLite interpreter to collect activation ranges
  4. Apply INT8 PTQ: quantize weights and activations
  5. Write INT8 .tflite via flatc

Output types:
  - input:  UINT8  (0..255, scale=1/255, zero_point=0)
  - output: FLOAT32 (dequantize at end for EAR calculation)
  - internal: INT8
"""

import json
import struct
import os
import subprocess
import sys
import numpy as np

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf

DIR = os.path.dirname(os.path.abspath(__file__))
JSON_PATH   = os.path.join(DIR, 'face_landmark.json')
TFLITE_SRC  = os.path.join(DIR, 'face_landmark.tflite')
OUT_F32     = os.path.join(DIR, 'face_landmark_f32.tflite')
OUT_F32_JSON = os.path.join(DIR, 'face_landmark_f32.json')
OUT_INT8    = os.path.join(DIR, 'face_landmark_int8.tflite')
SCHEMA      = os.path.join(DIR, 'schema.fbs')
FLATC       = '/opt/homebrew/bin/flatc'
CALIB_NPY   = '/tmp/calib_faces.npy'

print(f"TF {tf.__version__}")

# ─── Step 1: Load JSON ────────────────────────────────────────────────────────
print("\nLoading model JSON...")
with open(JSON_PATH) as f:
    model = json.load(f)

sg = model['subgraphs'][0]
tensors = sg['tensors']
operators = sg['operators']
op_codes = model['operator_codes']
buffers = model['buffers']

print(f"  Tensors: {len(tensors)}, Ops: {len(operators)}, Buffers: {len(buffers)}")

# Op code lookup: deprecated_builtin_code values
# 0=ADD, 3=CONV_2D, 4=DEPTHWISE_CONV_2D, 6=DEQUANTIZE, 17=MAX_POOL_2D, 34=PAD, 45=STRIDED_SLICE, 54=PRELU
def get_opcode(op):
    return op_codes[op['opcode_index']]['deprecated_builtin_code']

dequant_ops = [(i, op) for i, op in enumerate(operators) if get_opcode(op) == 6]
print(f"  DEQUANTIZE ops: {len(dequant_ops)}")

from collections import Counter
types = Counter(t.get('type','?') for t in tensors)
print(f"  Tensor types: {dict(types)}")

# ─── Step 2: Graph surgery – convert FLOAT16 buffers to FLOAT32 ───────────────
print("\nGraph surgery: FLOAT16 → FLOAT32...")

# Build mapping: DEQUANTIZE output tensor → input tensor
dequant_remap = {}  # output_idx → input_idx
for i, op in dequant_ops:
    inp_idx = op['inputs'][0]
    out_idx = op['outputs'][0]
    dequant_remap[out_idx] = inp_idx

# Convert FLOAT16 tensors (inputs to DEQUANTIZE) to FLOAT32
f16_converted = 0
for t_idx, t in enumerate(tensors):
    if t.get('type') == 'FLOAT16':
        buf_idx = t['buffer']
        buf = buffers[buf_idx]
        if 'data' in buf and buf['data']:
            data_bytes = bytes(buf['data'])
            n_elements = len(data_bytes) // 2
            f16_vals = struct.unpack(f'{n_elements}e', data_bytes)
            f32_bytes = struct.pack(f'{n_elements}f', *f16_vals)
            buf['data'] = list(f32_bytes)
        t['type'] = 'FLOAT32'
        f16_converted += 1

print(f"  Converted {f16_converted} FLOAT16 tensors to FLOAT32")

# Update all ops: replace references to DEQUANTIZE outputs with the original input
for op in operators:
    new_inputs = []
    for idx in op.get('inputs', []):
        new_inputs.append(dequant_remap.get(idx, idx))
    op['inputs'] = new_inputs
    new_outputs = []
    for idx in op.get('outputs', []):
        new_outputs.append(dequant_remap.get(idx, idx))
    op['outputs'] = new_outputs

# Update subgraph inputs/outputs
sg['inputs']  = [dequant_remap.get(i, i) for i in sg.get('inputs', [])]
sg['outputs'] = [dequant_remap.get(i, i) for i in sg.get('outputs', [])]

# Remove DEQUANTIZE ops
dequant_indices = set(i for i, _ in dequant_ops)
sg['operators'] = [op for i, op in enumerate(operators) if i not in dequant_indices]
operators = sg['operators']
print(f"  Remaining ops: {len(operators)}")

# Write F32 JSON and compile to .tflite
print("\nWriting FLOAT32 model JSON...")
with open(OUT_F32_JSON, 'w') as f:
    json.dump(model, f)

print("Compiling FLOAT32 .tflite...")
result = subprocess.run(
    [FLATC, '-b', '--schema', SCHEMA, '--json', OUT_F32_JSON, '-o', DIR],
    capture_output=True, text=True
)
if result.returncode != 0:
    print(f"flatc error: {result.stderr}")
    sys.exit(1)

# flatc outputs to same name as JSON but .bin, rename
compiled_path = OUT_F32_JSON.replace('.json', '.bin')
if os.path.exists(compiled_path):
    os.rename(compiled_path, OUT_F32)
else:
    # flatc might output with different name
    for f in os.listdir(DIR):
        if f.endswith('.bin'):
            os.rename(os.path.join(DIR, f), OUT_F32)
            break

if not os.path.exists(OUT_F32):
    print("ERROR: flatc did not produce output file")
    print("flatc stdout:", result.stdout)
    print("flatc stderr:", result.stderr)
    print("Directory contents:", os.listdir(DIR))
    sys.exit(1)

print(f"  Saved FLOAT32 model: {OUT_F32} ({os.path.getsize(OUT_F32):,} bytes)")

# ─── Step 3: Verify FLOAT32 model ────────────────────────────────────────────
print("\nVerifying FLOAT32 model...")
interp = tf.lite.Interpreter(model_path=OUT_F32)
interp.allocate_tensors()
inp = interp.get_input_details()[0]
outs = interp.get_output_details()
print(f"  Input:  {inp['shape']} {inp['dtype'].__name__}")
for o in outs:
    print(f"  Output: {o['shape']} {o['dtype'].__name__}")

# ─── Step 4: Calibration ─────────────────────────────────────────────────────
print("\nRunning calibration...")

# Load calibration data
if os.path.exists(CALIB_NPY):
    calib_imgs = np.load(CALIB_NPY)
    print(f"  Loaded {len(calib_imgs)} calibration images from {CALIB_NPY}")
else:
    print("  No calib_faces.npy found, generating synthetic data")
    rng = np.random.default_rng(42)
    calib_imgs = rng.normal(0.6, 0.15, (100, 192, 192, 3)).astype(np.float32).clip(0, 1)

# ─── Step 5: TFLiteConverter INT8 using representative_dataset ───────────────
# Since we have a pure FLOAT32 .tflite, wrap it for TFLiteConverter
print("\nQuantizing to INT8 via TFLiteConverter...")

# We need a concrete TF function. Use tf.saved_model approach via numpy function wrapper.
# The key insight: we can use from_concrete_functions with a proper tf.function.

@tf.function(input_signature=[tf.TensorSpec([1, 192, 192, 3], tf.float32)])
def landmark_fn(x):
    def _run(x_np):
        i2 = tf.lite.Interpreter(model_path=OUT_F32)
        i2.allocate_tensors()
        id2 = i2.get_input_details()[0]
        od2 = i2.get_output_details()
        i2.set_tensor(id2['index'], x_np.numpy())
        i2.invoke()
        lm = i2.get_tensor(od2[0]['index'])   # [1,1,1,1404]
        sc = i2.get_tensor(od2[1]['index'])   # [1,1,1,1]
        return lm.reshape(1, 1404), sc.reshape(1, 1)
    lm, sc = tf.py_function(_run, [x], [tf.float32, tf.float32])
    lm.set_shape([1, 1404])
    sc.set_shape([1, 1])
    return lm, sc

def representative_dataset():
    for img in calib_imgs:
        yield [img.reshape(1, 192, 192, 3)]

concrete_fn = landmark_fn.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_fn], landmark_fn)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
    tf.lite.OpsSet.TFLITE_BUILTINS,
]
converter.inference_input_type  = tf.uint8
converter.inference_output_type = tf.float32

try:
    print("  Converting (this may take several minutes)...")
    q_model = converter.convert()
    with open(OUT_INT8, 'wb') as f:
        f.write(q_model)
    print(f"\n  Saved INT8 model: {OUT_INT8} ({len(q_model):,} bytes)")

    # Verify
    iv = tf.lite.Interpreter(model_content=q_model)
    iv.allocate_tensors()
    for d in iv.get_input_details():
        print(f"  IN:  {d['shape']} {d['dtype']}")
    for d in iv.get_output_details():
        print(f"  OUT: {d['shape']} {d['dtype']}")
    print("\nDone!")

except Exception as e:
    print(f"\n  Full INT8 conversion failed: {e}")
    print("  Trying dynamic range quantization (weights only)...")

    converter2 = tf.lite.TFLiteConverter.from_concrete_functions([concrete_fn], landmark_fn)
    converter2.optimizations = [tf.lite.Optimize.DEFAULT]
    try:
        q2 = converter2.convert()
        with open(OUT_INT8, 'wb') as f:
            f.write(q2)
        print(f"  Saved dynamic-range model: {OUT_INT8} ({len(q2):,} bytes)")
    except Exception as e2:
        print(f"  Dynamic range also failed: {e2}")
        sys.exit(1)
